# Generated by Django 4.2.20 on 2025-05-07 22:30

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("treatments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="treatmentguide",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="treatmentguide",
            index=models.Index(
                fields=["created_by"], name="treatment_g_created_aa3169_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="treatmentguide",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["factors"], name="factors_gin_idx", opclasses=["jsonb_path_ops"]
            ),
        ),
    ]
