# Generated by Django 4.2.20 on 2025-05-07 22:30

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomDrug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=20)),
                ("active_ingredient", models.CharField(max_length=20)),
                (
                    "contraindications",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "measurement_value",
                    models.DecimalField(
                        decimal_places=5,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00001"))
                        ],
                    ),
                ),
                (
                    "per_weight_value",
                    models.DecimalField(
                        decimal_places=5,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00001"))
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "Custom Drug",
                "verbose_name_plural": "Custom Drugs",
                "db_table": "custom_drug",
            },
        ),
        migrations.CreateModel(
            name="Drug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=20)),
                ("active_ingredient", models.CharField(max_length=20)),
                (
                    "contraindications",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "measurement_value",
                    models.DecimalField(
                        decimal_places=5,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00001"))
                        ],
                    ),
                ),
                (
                    "per_weight_value",
                    models.DecimalField(
                        decimal_places=5,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00001"))
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "Drug",
                "verbose_name_plural": "Drugs",
                "db_table": "drug",
            },
        ),
    ]
