# Generated by Django 4.2.20 on 2025-05-07 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_initial"),
        ("drugs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="drug",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="drug",
            name="measurement_unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_measurement_unit",
                to="common.unit",
            ),
        ),
        migrations.AddField(
            model_name="drug",
            name="per_weight_unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_per_weight_unit",
                to="common.unit",
            ),
        ),
        migrations.AddField(
            model_name="drug",
            name="species",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="common.species"
            ),
        ),
        migrations.AddField(
            model_name="customdrug",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customdrug",
            name="measurement_unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_measurement_unit",
                to="common.unit",
            ),
        ),
        migrations.AddField(
            model_name="customdrug",
            name="per_weight_unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_per_weight_unit",
                to="common.unit",
            ),
        ),
        migrations.AddField(
            model_name="customdrug",
            name="species",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="common.species"
            ),
        ),
        migrations.AddField(
            model_name="customdrug",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_drugs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="drug",
            index=models.Index(fields=["name"], name="drug_name_461ac2_idx"),
        ),
        migrations.AddIndex(
            model_name="drug",
            index=models.Index(
                fields=["active_ingredient"], name="drug_active__f069be_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customdrug",
            index=models.Index(fields=["user"], name="custom_drug_user_id_590e38_idx"),
        ),
    ]
