# Generated by Django 4.2.20 on 2025-05-07 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    # initial = True

    dependencies = [
        ("common", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="systemlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="system_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="species",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="rating",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="rating",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="systemlog",
            index=models.Index(
                fields=["timestamp"], name="system_log_timesta_2209e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="systemlog",
            index=models.Index(fields=["source"], name="system_log_source_2fd3a3_idx"),
        ),
        migrations.AddIndex(
            model_name="systemlog",
            index=models.Index(
                fields=["log_level"], name="system_log_log_lev_2688fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="systemlog",
            index=models.Index(fields=["user"], name="system_log_user_id_fcedc2_idx"),
        ),
        migrations.AddIndex(
            model_name="rating",
            index=models.Index(
                fields=["content_type", "object_id"], name="rating_content_4f5bbe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rating",
            index=models.Index(fields=["created_by"], name="rating_created_8f2c94_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="rating",
            unique_together={("created_by", "content_type", "object_id")},
        ),
    ]
