# Generated by Django 4.2.20 on 2025-05-07 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DrugInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("query", models.TextField()),
                ("result", models.TextField()),
                ("context", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "verbose_name": "Drug Interaction",
                "verbose_name_plural": "Drug Interactions",
                "db_table": "drug_interaction",
            },
        ),
    ]
