# Generated by Django 4.2.20 on 2025-05-07 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("drugs", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("interactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="druginteraction",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="druginteraction",
            name="drugs",
            field=models.ManyToManyField(related_name="interactions", to="drugs.drug"),
        ),
        migrations.AddIndex(
            model_name="druginteraction",
            index=models.Index(
                fields=["created_by"], name="drug_intera_created_825a7b_idx"
            ),
        ),
    ]
