# Generated by Django 5.0.7 on 2025-04-13 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_delete_user"),
    ]

    def create_rls_functions(apps, schema_editor):
        if schema_editor.connection.vendor != 'postgresql':
            return

        # Create functions for RLS policies
        schema_editor.execute("""
            -- Function to get the current user ID from session variables
            CREATE OR REPLACE FUNCTION current_user_id()
            RETURNS integer
            LANGUAGE sql
            STABLE
            AS $$
                SELECT nullif(current_setting('app.current_user_id', true), '')::integer;
            $$;

            -- Function to check if current user has admin role
            CREATE OR REPLACE FUNCTION current_user_has_role(role text)
            RETURNS boolean
            LANGUAGE sql
            STABLE
            AS $$
                SELECT CASE 
                    WHEN current_setting('app.is_admin', true) = 'true' THEN true
                    ELSE false
                END;
            $$;
        """)

    def remove_rls_functions(apps, schema_editor):
        if schema_editor.connection.vendor != 'postgresql':
            return

        schema_editor.execute("""
            DROP FUNCTION IF EXISTS current_user_id();
            DROP FUNCTION IF EXISTS current_user_has_role(text);
        """)

    operations = [
        migrations.RunPython(create_rls_functions, remove_rls_functions)
    ]
