# Generated by Django 4.2.20 on 2025-04-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_add_generic_rating_model"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="usersearchhistory",
            name="user_search_user_id_60889e_idx",
        ),
        migrations.RemoveIndex(
            model_name="usersearchhistory",
            name="user_search_module_77dc4e_idx",
        ),
        migrations.RemoveIndex(
            model_name="usersearchhistory",
            name="user_search_user_id_57075c_idx",
        ),
        migrations.RemoveIndex(
            model_name="usersearchhistory",
            name="user_search_created_dbde9f_idx",
        ),
        migrations.RemoveField(
            model_name="usersearchhistory",
            name="user",
        ),
        migrations.AlterField(
            model_name="usersearchhistory",
            name="module",
            field=models.CharField(
                db_index=True,
                help_text="Module identifier (e.g., 'drug-interaction', 'dosage-calc', 'treatment-guide')",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="usersearchhistory",
            name="query",
            field=models.TextField(help_text="The search query or interaction content"),
        ),
        migrations.AddIndex(
            model_name="usersearchhistory",
            index=models.Index(
                fields=["-created_at"], name="user_search_created_08fede_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersearchhistory",
            index=models.Index(
                fields=["created_by", "-created_at"],
                name="user_search_created_d4cdf2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="usersearchhistory",
            index=models.Index(
                fields=["created_by", "module", "-created_at"],
                name="user_search_created_9749cd_idx",
            ),
        ),
    ]
